##Vercor Arithmetic

In [6]:
import numpy as np 

In [7]:


a = np.array([20,30,40])
b = np.array([10,20,30])

#Vector Addition

In [8]:
a + b

array([30, 50, 70])

##vector Substraction

In [9]:
a -b 

array([10, 10, 10])

##vertor multiplication

In [10]:
a * b

array([ 200,  600, 1200])

##Vector Division

In [11]:
a / b

array([2.        , 1.5       , 1.33333333])

##vector remainder

In [12]:
a % b

array([ 0, 10, 10])